name: Build
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install hatch
      - run: hatch build
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/*
